### ISSUE TITLE
Redirect after session timeout

### ISSUE THREAD

**Issue by igler** [basti1302/traverson-angular#17]
I am getting a <code>401</code> on an api call when the session has expired. With <code>$http</code> from Angular you could use an interceptor doing a forward to the login page. How can this be achieved as traverson-angular uses the superagent client? BTW, don't want to fallback to $http.

**Comment by basti1302** [comment]
Check https://github.com/basti1302/traverson-angular/blob/master/readme.markdown#using-angularjs-http-service-instead-of-traversons-http-module

You can tell traverson-angular to use $http internally instead of superagent. With this option enabled, all features like interceptors etc. can be used.

Hope that helps. Feel free to reopen if not.

**Comment by igler** [comment]
But if I don' t want to fallback on $http and continue to use superagent? Do you see any chance to find a solution with this module? Maybe a plugin or so?

**Comment by basti1302** [comment]
Why would you insist on having traverson-angular using superagent?? I do not see any elegant solution for this without interceptors. 

Of course you could always check for the http status code when traverson-angular's promise resolves. When it is 401 you could trigger the redirect manually. But that sounds cumbersome.

**Comment by igler** [comment]
But suing <code>.useAngularHttp()</code> needs to be done on every requestBuilder, too? Or is there a possibility to configure this globally?
